import { mkdir, readFile, writeFile, cp, readdir, stat } from 'node:fs/promises';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { landing } from './content/landing.mjs';
import { pages, code, escape } from './content/pages.mjs';
const root=dirname(fileURLToPath(import.meta.url));
const out=join(root,'out');
const repo='https://github.com/manyeya/vibes';
const arrow='<span aria-hidden="true">↗</span>';
const mark='<svg viewBox="0 0 32 26" fill="none" aria-hidden="true"><path d="M3 12v3M9 5v16M16 2v22M23 6v14M29 11v5" stroke="currentColor" stroke-width="3" stroke-linecap="round"/></svg>';
const brand=(base)=>`<a href="${base}" class="brand" aria-label="Vibes home">${mark}<span>vibes<span class="brand-period">.</span></span></a>`;
function header(base,docs=false){return `<header class="site-header">${brand(base)}<span class="header-tag">${docs?'DOCUMENTATION':'AN AGENT. A TEAM. A LITTLE MOMENTUM.'}</span><nav aria-label="Main navigation"><a href="${base}docs/introduction/" ${docs?'aria-current="true"':''}>Documentation</a><a href="${repo}" target="_blank" rel="noopener noreferrer">GitHub ${arrow}</a><button class="search-trigger" data-search-open aria-label="Search documentation"><span>Search docs</span><kbd>⌘ K</kbd><span class="search-small" aria-hidden="true">⌕</span></button><button class="theme-toggle" data-theme-toggle aria-label="Switch to dark theme">◐</button></nav></header>`;}
function search(base){return `<dialog class="search-dialog" id="search-dialog" aria-labelledby="search-title"><div class="search-top"><span aria-hidden="true">⌕</span><label class="sr-only" id="search-title" for="search-input">Search documentation</label><input id="search-input" type="search" autocomplete="off" placeholder="What would you like to know?" aria-controls="search-results"><button data-search-close aria-label="Close search">Esc</button></div><div id="search-results" aria-live="polite"><p>Find a guide, command, or concept.</p></div><div class="search-footer">↑ ↓ to navigate <span>Enter to open · Esc to close</span></div></dialog>`;}
function footer(base){return `<footer class="site-footer">${brand(base)}<span>Open source. Built together.</span><a href="${base}docs/contributing/">Contribute ${arrow}</a><a href="${repo}/blob/main/LICENSE" target="_blank" rel="noopener noreferrer">MIT License ${arrow}</a><small>© ${new Date().getFullYear()} Vibes</small></footer>`;}
function shell(title,desc,body,base,slug=''){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>${escape(title)}</title><meta name="description" content="${escape(desc)}"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(desc)}"><meta property="og:type" content="website"><meta property="og:image" content="https://manyeya.github.io/vibes/assets/social.png"><link rel="canonical" href="https://manyeya.github.io/vibes/${slug}"><link rel="icon" type="image/svg+xml" href="${base}assets/favicon.svg"><script>try{if(localStorage.getItem('vibes-docs-theme')==='dark')document.documentElement.dataset.theme='dark'}catch{}</script><link rel="stylesheet" href="${base}assets/site.css"><script defer src="${base}assets/site.js"></script>${body.includes('class="v-nav"')?`<link rel="stylesheet" href="${base}assets/landing.css"><script defer src="${base}assets/landing.js"></script>`:''}</head><body data-base="${base}" ${body.includes('class="v-nav"')?'class="v-landing"':''}><a class="skip-link" href="#main">Skip to content</a>${body}${search(base)}<div id="site-status" class="sr-only" role="status"></div></body></html>`;}
function home(){return shell('Vibes — Give your ideas backup.','An open-source AI coding agent with a team behind it. Plan, delegate, build, and review in your terminal.',landing(repo),'./');}
function docs(page,index){const base='../../';const sidebar=[...new Set(pages.map(p=>p.group))].map(group=>`<div class="sidebar-group"><p>${group}</p>${pages.filter(p=>p.group===group).map(p=>`<a href="../${p.slug}/" ${p.slug===page.slug?'aria-current="page"':''}>${p.title}</a>`).join('')}</div>`).join('');const toc=page.sections.map(s=>`<a href="#${s.id}">${s.title}</a>`).join('');return shell(`${page.title} — Vibes docs`,page.description,`${header(base,true)}<div class="docs-mobile-bar"><button data-sidebar-toggle aria-expanded="false" aria-controls="docs-sidebar">☰ <span>Documentation</span></button><span>${page.title}</span></div><div class="docs-layout"><aside id="docs-sidebar" aria-label="Documentation navigation"><a class="sidebar-home" href="${base}">← Back to Vibes</a>${sidebar}<a class="sidebar-source" href="${repo}" target="_blank" rel="noopener noreferrer">View source ${arrow}</a></aside><main id="main" class="doc-content"><div class="doc-breadcrumb">DOCS <span>/</span> ${page.group.toUpperCase()}</div><h1>${page.title}</h1><p class="doc-description">${page.description}</p><div class="doc-divider"></div>${page.sections.map(s=>`<section id="${s.id}"><h2><a href="#${s.id}">${s.title}</a></h2>${s.html}</section>`).join('')}<div class="doc-edit"><a href="${repo}/edit/main/apps/docs-site/content/pages.mjs" target="_blank" rel="noopener noreferrer">Improve this page ${arrow}</a><span>Grounded in the Vibes source.</span></div><nav class="page-neighbors" aria-label="Previous and next pages">${index>0?`<a href="../${pages[index-1].slug}/"><span>← PREVIOUS</span><strong>${pages[index-1].title}</strong></a>`:'<span></span>'}${index<pages.length-1?`<a href="../${pages[index+1].slug}/"><span>NEXT →</span><strong>${pages[index+1].title}</strong></a>`:''}</nav></main><aside class="doc-toc" aria-label="On this page"><p>ON THIS PAGE</p>${toc}<a class="toc-help" href="${repo}/issues" target="_blank" rel="noopener noreferrer">Have a question? ${arrow}</a></aside></div>${footer(base)}`,base,`docs/${page.slug}/`);}
await mkdir(out,{recursive:true});await cp(join(root,'assets'),join(out,'assets'),{recursive:true});await writeFile(join(out,'.nojekyll'),'');await writeFile(join(out,'index.html'),home());
for(const [index,page] of pages.entries()){const target=join(out,'docs',page.slug);await mkdir(target,{recursive:true});await writeFile(join(target,'index.html'),docs(page,index));}
const plain=s=>s.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').replaceAll('&gt;','>').replaceAll('&lt;','<').replaceAll('&quot;','"').trim();
await writeFile(join(out,'search-index.json'),JSON.stringify(pages.flatMap(p=>[{title:p.title,group:p.group,description:p.description,text:plain(p.sections.map(s=>s.html).join(' ')),url:`docs/${p.slug}/`},...p.sections.map(s=>({title:s.title,group:p.title,description:plain(s.html).slice(0,210),text:plain(s.html),url:`docs/${p.slug}/#${s.id}`}))])));
await writeFile(join(out,'404.html'),shell('Page not found — Vibes','Find your way back to the Vibes documentation.',`${header('/vibes/')}<main id="main" class="not-found"><span class="eyebrow">404 / WRONG TURN, GOOD COMPANY</span><h1>Let’s find<br>your way back.</h1><p>That page isn’t here. The docs are a good place to start.</p><a class="button primary" href="/vibes/docs/introduction/">Open the documentation ↗</a></main>`,'/vibes/'));
await writeFile(join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['',...pages.map(p=>`docs/${p.slug}/`)].map(path=>`<url><loc>https://manyeya.github.io/vibes/${path}</loc></url>`).join('')}</urlset>`);
// Validate every generated internal link, including section anchors, before deployment.
const allHtml=[join(out,'index.html'),...pages.map(p=>join(out,'docs',p.slug,'index.html'))];let checked=0;
for(const file of allHtml){const html=await readFile(file,'utf8');for(const match of html.matchAll(/(?:href|src)="([^"]+)"/g)){const href=match[1];if(/^(https?:|mailto:|data:)/.test(href))continue;const [path,hash]=href.split('#');let target=path?resolve(dirname(file),path):file;const info=await stat(target).catch(()=>null);if(info?.isDirectory())target=join(target,'index.html');const data=await readFile(target,'utf8').catch(()=>null);if(data===null)throw new Error(`Broken link: ${file} → ${href}`);if(hash&&!data.includes(`id="${hash}"`))throw new Error(`Missing anchor: ${href}`);checked++;}}
console.log(`Built ${pages.length+1} pages, search index, sitemap, and 404. Validated ${checked} local links and assets.`);
