export const escape = text => String(text).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export const code = (text, language='shell') => `<div class="code-block"><div class="code-toolbar"><span>${language}</span><button data-copy aria-label="Copy code">Copy <span aria-hidden="true">⧉</span></button></div><pre><code>${escape(text)}</code></pre></div>`;
const section = (id,title,html) => ({id,title,html});
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(cell=>`<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
export const pages = [
{slug:'introduction',title:'Meet Vibes',group:'Start here',description:'A coding agent with a team behind it. Your terminal, your tools, your call.',sections:[
section('what-is-vibes','From an idea to working code',`<p>Vibes is an open-source AI coding orchestrator. It works inside a project with real file and shell tools, delegates focused work to sub-agents, and keeps you in control through execution modes.</p><p>You can use the terminal interface, the web interface, or build on the agent framework directly. All three share the same runtime.</p><div class="callout"><strong>Start with your own project</strong><p>Install from the repository, connect a model provider, and run <code>vibes</code> in the directory you want to work on.</p><a href="../getting-started/">Follow the quick start →</a></div>`),
section('capabilities','What it can do',`<ul><li><strong>Work with code:</strong> read, write, edit, and inspect files; run real host commands.</li><li><strong>Delegate:</strong> send bounded work to focused sub-agents and bring the results back.</li><li><strong>Plan:</strong> persist plans and tasks, and request your review before execution.</li><li><strong>Remember:</strong> maintain a session scratchpad and a searchable note store.</li><li><strong>Create artifacts:</strong> render HTML, Markdown, Mermaid diagrams, and charts.</li><li><strong>Extend:</strong> add tools and lifecycle behavior through plugins and skills.</li></ul>`),
section('architecture','One core, three front doors',`<p>The framework lives in <code>packages/harness-vibes</code>. A Hono API, an OpenTUI terminal interface, and a React web app provide different ways to work with it.</p><p>Vibes owns its agent loop and implements the AI SDK v7 Agent interface. The SDK handles each individual model call; Vibes handles iteration, context, plugins, steering, and stopping.</p><a class="inline-next" href="../architecture/">Understand the architecture ↗</a>`)]},
{slug:'getting-started',title:'Your first session',group:'Start here',description:'Install Vibes, connect a provider, and start working in a repository.',sections:[
section('prerequisites','Before you start',`<p>You need <strong>Bun 1.3 or newer</strong>, Git, and a model-provider API key. Vibes currently installs from a checkout; a standalone cross-platform binary is not shipped.</p>${code('bun --version\ngit --version')}`),
section('install','01 — Install from source',`${code('git clone https://github.com/manyeya/vibes.git\ncd vibes\nbun install\nbun link')}<p><code>bun link</code> makes the <code>vibes</code> command available. Keep this checkout: the launcher uses its API and terminal application.</p>`),
section('provider','02 — Connect a model',`${code('vibes login OPENAI_API_KEY')}<p>The login prompt hides your input. You can use <code>AI_GATEWAY_API_KEY</code>, <code>ZHIPU_API_KEY</code>, <code>OPENAI_API_KEY</code>, or <code>OPENROUTER_API_KEY</code>. Running <code>vibes login</code> without a name defaults to OpenRouter.</p><p>Run <code>vibes keys</code> to inspect the storage backend and saved key names. It does not print the keys themselves.</p>`),
section('launch','03 — Open your project',`${code('cd ~/projects/your-project\nvibes')}<p>The launcher starts a local API on an available port and opens the terminal interface in your current directory. Runtime data lives under <code>~/.vibes/</code>. The API stops when the launcher exits.</p><div class="prompt-example"><span>TRY A FIRST PROMPT</span><p>“Explain how this project is organized. Identify the main entry points and suggest a small improvement.”</p></div>`),
section('control','Choose how much autonomy to give',`<p>Use <strong>plan</strong> to explore without edits, <strong>manual</strong> to approve each edit or command, <strong>auto-edit</strong> to allow file changes while reviewing commands, or <strong>auto</strong> for autonomous execution.</p><a class="inline-next" href="../execution-modes/">Compare execution modes ↗</a>`),
section('troubleshooting','If something does not start',`<ul><li><strong>Command not found:</strong> run <code>bun link</code> in the Vibes checkout and ensure Bun’s bin directory is on your PATH.</li><li><strong>No model-provider key:</strong> run <code>vibes keys</code>, then <code>vibes login</code> for your provider.</li><li><strong>API or terminal startup:</strong> inspect <code>~/.vibes/vibes-cli.log</code>.</li><li><strong>Custom installation:</strong> use <code>--home</code> or <code>--api-url</code> as described in the CLI reference.</li></ul>`)]},
{slug:'cli',title:'CLI reference',group:'Start here',description:'Launch anywhere. Manage providers. Keep the setup simple.',sections:[
section('launch','Launch options',`${code('vibes [--port <number>] [--home <directory>] [--api-url <url>]')}${table(['Option','Behavior'],[['<code>--help, -h</code>','Print command help.'],['<code>--version, -v</code>','Print the installed checkout version.'],['<code>--port &lt;n&gt;</code>','Choose the local API port instead of an available ephemeral port.'],['<code>--home &lt;dir&gt;</code>','Use a custom state directory. The default is <code>~/.vibes</code>; <code>VIBES_HOME</code> can also configure it.'],['<code>--api-url &lt;url&gt;</code>','Connect to an existing API instead of starting one.']])}`),
section('credentials','Credential commands',`${code('vibes login                     # OpenRouter by default\nvibes login OPENAI_API_KEY      # Choose a provider\nvibes keys                      # List names, not values\nvibes keys add OPENAI_API_KEY\nvibes keys rm OPENAI_API_KEY\nvibes logout                    # Clear stored credentials')}<p>Environment variables take precedence over saved keys. Desktop systems use the OS keychain when available; the fallback is an encrypted file under the Vibes home directory.</p><a href="../configuration/">Read configuration and storage details →</a>`),
section('development','Run the apps separately',`${code('bun run dev:api\n# In another terminal:\nbun run dev:tui\n# Or use the web interface:\nbun run dev:demo')}<p>The development API defaults to port 3000. The web app proxies <code>/api/*</code> to it. The terminal development command expects that API to be running.</p>`),
section('bundles','Build local bundles',`${code('bun run vibes:build')}<p>This bundles the API and terminal entry points into <code>dist/</code>. The launcher prefers these bundles when present. OpenTUI’s native renderer remains a runtime dependency.</p>`)]},
{slug:'configuration',title:'Configuration',group:'Start here',description:'Model providers, credential storage, and the directories Vibes uses.',sections:[
section('providers','Provider resolution',`<p>The API selects the first configured provider in this order:</p><ol><li><code>AI_GATEWAY_API_KEY</code></li><li><code>ZHIPU_API_KEY</code></li><li><code>OPENAI_API_KEY</code></li><li><code>OPENROUTER_API_KEY</code></li></ol><p>Model availability and defaults are defined in <code>apps/api/src/model-factory.ts</code>. If you have several keys configured, account for this order when troubleshooting model selection.</p>`),
section('environment','Environment variables',`${code('OPENAI_API_KEY=your-provider-key\nPORT=3000\nNODE_ENV=development\nSKILLS_DIR=./skills','env')}<p>For development, place configuration in a local <code>.env</code> file. The launcher also accepts environment variables and stored credentials. Keep credentials out of source control.</p>${table(['Variable','Purpose'],[['<code>VIBES_HOME</code>','Override the launcher’s runtime-data directory.'],['<code>SKILLS_DIR</code>','Optional directory for discoverable skills.'],['<code>EXA_API_KEY</code>','Enable Exa web search.'],['<code>TAVILY_API_KEY</code>','Enable Tavily web search.'],['<code>BRAVE_API_KEY</code>','Enable Brave web search.']])}`),
section('storage','Where credentials live',`<p>Vibes attempts to use the OS keychain: Keychain on macOS, Credential Manager on Windows, and Secret Service on supported Linux desktops. Where this is unavailable, it falls back to AES-256-GCM encrypted credentials in <code>~/.vibes/credentials.json</code>.</p><p>The fallback uses <code>CREDENTIAL_ENCRYPTION_KEY</code> when configured, otherwise a locally generated key file. Since that key can live beside the encrypted file, this fallback does not protect against an attacker who can read both. Environment variables are useful for CI because nothing needs to be stored.</p>`),
section('state','Runtime state',`<p>Launching <code>vibes</code> keeps runtime data under <code>~/.vibes/</code> by default. Direct API development uses the configured workspace paths. Sessions persist in SQLite and have their own agent instance and state. Shared memories are separate from the session scratchpad.</p>`)]},
{slug:'execution-modes',title:'Execution modes',group:'Work with Vibes',description:'Decide what the agent can do, and where it should stop for your input.',sections:[
section('modes','Four levels of control',table(['Mode','File edits','Shell and delegation','Best for'],[['<code>plan</code>','Read-only','Restricted by read-only policy','Exploration and proposing changes.'],['<code>manual</code>','Approval required','Approval required','Reviewing each change and command.'],['<code>auto-edit</code>','Allowed automatically','Approval required','Moving quickly through code changes.'],['<code>auto</code>','Allowed automatically','Allowed automatically','Tasks with clear scope and trusted execution.']])),
section('switching','Switch modes during a session',`<p>The UI and API can change the mode while a session is active. The agent also has a <code>set_mode</code> tool. The mode is a policy layer over the tool-approval gate, rather than a different agent implementation.</p><p>To set it in a streaming API request, include a <code>mode</code> field alongside the messages.</p>${code('{\n  "messages": [{ "role": "user", "content": "Explain this repository" }],\n  "mode": "plan"\n}','json')}`),
section('planning','Planning and clarification',`<p>A plan can be offered for review before implementation. Vibes can also call <code>ask_user</code> with a structured questionnaire. That halts the run until your response arrives, keeping decisions in the conversation instead of guessing.</p>`),
section('boundaries','Understand the execution boundary',`<p>Structured file operations are contained within the workspace by the sandbox. Shell commands run real host binaries. A working directory is not an operating-system jail, so choose an execution mode appropriate to the repository and task.</p>`)]},
{slug:'sub-agents',title:'Sub-agents',group:'Work with Vibes',description:'Focused workers that turn one large task into smaller, concrete pieces.',sections:[
section('delegation','Delegate a bounded piece of work',`<p>The main agent can delegate through <code>task</code>, <code>delegate</code>, and <code>parallel_delegate</code>. Each worker has a specific system prompt and tool allowlist, and reports a result to the parent.</p><div class="prompt-example"><span>EXAMPLE REQUEST</span><p>“Review the authentication flow. Delegate an independent review of the tests, then combine the findings.”</p></div><p>Sub-agents use a lean plugin set focused on files, shell, skills, artifacts, and planning. They do not duplicate the main agent’s full memory and summarization setup.</p>`),
section('specialists','Create specialists at runtime',`${table(['Tool','Purpose'],[['<code>create_agent</code>','Define a specialist for later work.'],['<code>spawn_agent</code>','Define and run a one-off specialist.'],['<code>list_agents</code>','Inspect the available roster.']])}<p>The registry is mutable: the main agent is not limited to a baked-in list. Workers can inherit custom tools configured for the parent.</p>`),
section('results','Results and completion',`<p>A worker can complete naturally with a final answer. It can optionally call <code>report_result</code> for a structured summary and file list. Results may be saved under <code>subagent_results/</code>.</p><p>Keep delegated tasks concrete: a question to answer, files to review, or a result to produce. Independent work is easier to combine than overlapping edits.</p>`)]},
{slug:'plugins-and-skills',title:'Plugins & skills',group:'Work with Vibes',description:'Extend what Vibes can do without expanding its core agent loop.',sections:[
section('plugins','Capabilities are plugins',`<p>Plugins contribute tools and lifecycle behavior. The flagship <code>createVibeAgent</code> assembles the default set; the core agent coordinates them.</p>${table(['Plugin','Responsibility'],[['FilesystemPlugin / BashPlugin','Files and real command execution.'],['PlanningPlugin / ModePlugin','Plans, task state, and execution policy.'],['SubAgentPlugin','Focused workers and runtime specialists.'],['MemoryPlugin / SummarizationPlugin','Working memory and context management.'],['ArtifactPlugin','Renderable outputs and stored artifacts.'],['ClarificationPlugin','Structured questions that pause a run.'],['SkillsPlugin / RepoContextPlugin','Load skills and project guidance.'],['WebSearchPlugin / GuardrailsPlugin','Optional search and output checks.']])}`),
section('lifecycle','The lifecycle',`<p><code>prepareTurn</code> adjusts a model call. <code>modifySystemPrompt</code> contributes instructions. <code>onStreamReady</code> and <code>onStreamFinish</code> observe streaming. <code>waitReady</code> supports initialization, and <code>onInputAvailable</code> handles tool input.</p><p>The older <code>prepareStep</code> name remains a compatibility alias. Prefer the vocabulary used in the current plugin interface at <code>src/core/agent/plugin-api.ts</code>.</p>`),
section('skills','Skills are written instructions',`<p>Skills are human-authored <code>SKILL.md</code> files that the agent discovers and activates. Configure a skills directory with <code>SKILLS_DIR</code> when running the API.</p><p>Project guidance from <code>AGENTS.md</code> and <code>CLAUDE.md</code> is loaded by the repository-context plugin. Keep these documents specific to the codebase.</p>`),
section('mcp','MCP is opt-in',`<p><code>McpPlugin</code> ships in the harness package and can expose connected MCP server tools. It is not included in the default flagship plugin roster. Add it deliberately when assembling an agent that needs those connections.</p>`)]},
{slug:'memory',title:'Memory & sessions',group:'Work with Vibes',description:'Stay oriented across a long task without carrying every detail into every prompt.',sections:[
section('sessions','Each session has its own agent',`<p>The runtime owns session lifecycle and caches one agent instance per session. The API’s stream coordinator owns transport state such as abort controllers and reconnect tracking.</p><p>Session data persists in SQLite through the storage backend. The repository includes a Drizzle backend and configuration for different storage environments.</p>`),
section('working-memory','A scratchpad and a note store',`<p>A per-session scratchpad keeps immediate working context. Long-term notes are searchable through <code>remember</code>, <code>recall</code>, <code>update_memory</code>, <code>forget</code>, and <code>list_memories</code>.</p><p>The prompt receives a compact index rather than the full note store. This keeps memory useful without making every model call carry all historical text.</p>`),
section('files','State you can inspect',`${code('scratchpad.md\nplan.md\ntasks.json\ntracked_files.json\nartifacts/\nsubagent_results/','text')}<p>These session files capture working context and outputs. The shared note store is separate from per-session state.</p>`),
section('context','Context management',`<p>Restorable compression swaps large content for file or path references. Rolling summaries help fit long conversations into the context window. Errors are preserved separately, and stable prompt prefixes support model-provider caching.</p>`)]},
{slug:'artifacts',title:'Artifacts & canvas',group:'Work with Vibes',description:'Create something you can see, inspect, and keep.',sections:[
section('formats','Renderable outputs',`<p>The artifact plugin creates HTML sites, Markdown documents, Mermaid diagrams, and charts. Artifacts stream to the web interface’s canvas panel and are saved beneath the session’s <code>artifacts/</code> directory.</p><div class="prompt-example"><span>TRY IT</span><p>“Create an HTML report showing the main modules in this project and how they connect.”</p></div>`),
section('web','Use the web interface',`${code('bun run dev:api\n# In another terminal:\nbun run dev:demo')}<p>The web app combines streaming chat with a canvas for rendered artifacts. It uses the same underlying agent runtime as the terminal interface.</p>`),
section('persistence','Keep the result',`<p>Artifacts are files, not just chat messages. You can inspect or reuse the generated outputs from their saved location. Creating an artifact does not automatically publish it to a hosting service.</p>`)]},
{slug:'architecture',title:'Architecture',group:'Reference',description:'The owned loop, the flagship agent, and the runtime that brings them together.',sections:[
section('layers','The main layers',table(['Layer','Implementation','Responsibility'],[['Owned loop','<code>runAgentLoop</code> / <code>streamModelStep</code>','Iteration, steering, context pruning, halt conditions.'],['Core agent','<code>VibesAgent</code>','Implements AI SDK’s Agent contract and coordinates collaborators.'],['Flagship agent','<code>VibeAgent</code> / <code>createVibeAgent</code>','Core agent with the default tools, plugins, and workers.'],['Runtime','<code>AgentRuntime</code> / <code>Session</code>','App-level sessions, agent caching, and workspaces.']])),
section('loop','Vibes owns the loop',`<p>Each model step uses the AI SDK’s <code>streamText</code> primitive with a single-step stop condition. Vibes owns the surrounding loop: plugin fan-out, tool orchestration, stop conditions, steering, and context handling.</p>${code('User message\n  → Session / AgentRuntime\n  → VibeAgent + plugins\n  → Owned agent loop\n      → model step\n      → tools / approvals / workers\n      → next step or halt\n  → streamed events + saved state','text')}`),
section('layout','Repository map',`${code('apps/api/                 Hono API + session transport\napps/tui/                 React + OpenTUI terminal client\napps/demo/                React web chat and canvas\npackages/harness-vibes/   Agent framework\nbin/vibes.ts             Project launcher','text')}<p>Keep new capabilities in plugins. Keep app-specific transport concerns in the front doors, and avoid making the agent class responsible for every subsystem.</p>`),
section('streaming','Streaming and events',`<p>Vibes’ typed UI data parts carry tool activity, agent progress, tasks, and artifacts over the AI SDK stream. The web interface integrates them with <code>useChat</code>. A headless event bus is available for observing runs without a UI.</p>`)]},
{slug:'api',title:'API reference',group:'Reference',description:'The local Hono API for sessions, streaming, and discovery.',sections:[
section('base','Base URL',`${code('http://localhost:3000/api','text')}<p>The launcher normally manages a local API on an available port. When developing the API independently, the default port is 3000.</p>`),
section('endpoints','Endpoints',table(['Method','Path','Purpose'],[['GET / POST','<code>/sessions</code>','List or create sessions.'],['GET / PATCH / DELETE','<code>/sessions/:id</code>','Inspect, update, or delete a session.'],['GET','<code>/sessions/:id/messages</code>','Read persisted conversation history.'],['POST','<code>/vibe/stream</code>','Start a streaming agent response.'],['GET','<code>/vibe/:sessionId/reconnect</code>','Reconnect to an active stream.'],['GET','<code>/agents</code>','Inspect the worker roster.'],['GET','<code>/workspaces/:id/git</code>','Read branch and working-tree status.'],['GET','<code>/health</code>','Check API health.']])),
section('request','A streaming request',`${code('curl -N http://localhost:3000/api/vibe/stream \\\n  -H "Content-Type: application/json" \\\n  -d \'{\n    "messages": [{ "role": "user", "content": "Explain this repository" }],\n    "mode": "plan"\n  }\'')}<p>Include <code>session_id</code> to continue a session. The response is a stream, not a single JSON document. Clients should consume the stream protocol rather than expecting one final response object.</p>`),
section('source','Read the source contract',`<p>Request validation and streaming endpoints live in <code>apps/api/src/routers/vibe.ts</code>. The API entry point, model factory, and stream coordinator define the remaining server behavior.</p><p>Use the repository’s web or terminal client as a reference when implementing reconnection, tool approvals, or custom data-part rendering.</p>`)]},
{slug:'contributing',title:'Contributing',group:'Reference',description:'Work on the framework, a front door, or a focused capability.',sections:[
section('setup','Set up the repository',`${code('git clone https://github.com/manyeya/vibes.git\ncd vibes\nbun install\nbun run dev:api')}<p>Run the terminal or web client in another terminal. Consult <code>CLAUDE.md</code>, <code>AGENTS.md</code>, and the current source for architecture conventions.</p>`),
section('checks','Build and test',`${code('bun run build\nbun run test\n\n# Focus on the harness\ncd packages/harness-vibes\nbun test')}<p>Choose checks that cover the behavior you change. Keep model-independent tests separate from experiments that require API keys.</p>`),
section('principles','Contribution principles',`<ul><li>Add capabilities through plugins and keep the owned loop focused.</li><li>Preserve streaming behavior and typed events.</li><li>Keep sessions isolated and runtime state out of source control.</li><li>Document tool policy and failure behavior alongside new functionality.</li><li>Use the current source when architecture notes disagree with an older example.</li></ul>`),
section('docs','Work on this site',`${code('node apps/docs-site/build.mjs\npython3 -m http.server 8080 --directory apps/docs-site/out')}<p>Documentation lives in <code>apps/docs-site/content/pages.mjs</code>. Shared styling and browser interactions live in <code>assets/</code>. The build has no package dependencies. GitHub Actions rebuilds and publishes the site when docs changes land on main.</p>`)]},
];
