import {
    type LanguageModel,
    type ModelMessage,
    type StopCondition,
    type Tool,
    type UIMessageStreamWriter,
    type StreamTextResult,
    type GenerateTextResult,
    type ToolSet,
    type StepResult,
} from 'ai';

// Re-export ModelMessage for plugin use
export type { ModelMessage };

/**
 * Tool approval policy — either a boolean or a predicate function whose
 * signature matches AI SDK's `Tool.needsApproval`. The context arg is
 * optional from the caller's perspective; TypeScript happily accepts
 * 1-arg predicates here.
 */
export type ToolApprovalPolicy =
    | boolean
    | ((
        input: unknown,
        context: {
            toolCallId: string;
            messages: ModelMessage[];
            experimental_context?: unknown;
        }
    ) => boolean | Promise<boolean>);

/**
 * Tool approval configuration.
 */
export type ToolsRequiringApprovalConfig =
    | string[]
    | Record<string, ToolApprovalPolicy>;

// Import streaming types
import type {
    PluginStreamContext,
    VibesUIMessage,
    VibesDataParts,
} from './streaming/streaming.js';
import type { BudgetConfig } from './agent/budgets.js';
import type { LoopDetectionConfig } from './agent/loop-detection.js';
import type { AdaptiveReasoningConfig } from './agent/reasoning.js';

// Re-export config types so consumers can configure them from the root.
export type { BudgetConfig, ModelPricing } from './agent/budgets.js';
export type { LoopDetectionConfig } from './agent/loop-detection.js';
export type { AdaptiveReasoningConfig } from './agent/reasoning.js';

/**
 * Types of tasks for categorization and filtering.
 */
export enum TaskType {
    /** User request tasks generated by PlanningPlugin */
    UserRequest = 'user_request',
    /** Subtasks created by the agent during task execution */
    SubTask = 'subtask',
    /** Error analysis tasks (e.g. from an error-handling flow) */
    ErrorAnalysis = 'error_analysis',
    /** Delegation tasks from SubAgentPlugin */
    Delegation = 'delegation',
    /** Background async work */
    Background = 'background',
}

/**
 * Task event types for the event listener system.
 */
export type TaskEventType = 'created' | 'updated' | 'completed' | 'failed';

/**
 * Task event listener callback type.
 */
export type TaskEventListener = (task: TaskItem) => void | Promise<void>;

/**
 * A single item in the agent's internal todo list.
 * @deprecated Consider using TaskItem for more advanced task management
 */
export interface TodoItem {
    /** Unique identifier for the todo item */
    id: string;
    /** Human-readable title of the task */
    title: string;
    /** Current status of the task */
    status: 'pending' | 'in_progress' | 'completed';
    /** Task priority level */
    priority: 'low' | 'medium' | 'high';
    /** ISO timestamp when the task was created */
    createdAt: string;
    /** ISO timestamp when the task was last updated */
    updatedAt?: string;
    /** ISO timestamp when the task was completed (if applicable) */
    completedAt?: string;
}

/**
 * A single item in the agent's advanced task management system.
 * Supports dependencies, blocking, references, and metadata.
 */
export interface TaskItem {
    /** Unique identifier for the task */
    id: string;
    /** Type/category of the task */
    type: TaskType;
    /** Human-readable title of the task */
    title: string;
    /** Detailed description of the task */
    description: string;
    /** Current status of the task */
    status: 'pending' | 'blocked' | 'in_progress' | 'completed' | 'failed';
    /** Task priority level */
    priority: 'low' | 'medium' | 'high' | 'critical';
    /** ISO timestamp when the task was created */
    createdAt: string;
    /** ISO timestamp when the task was last updated */
    updatedAt: string;
    /** ISO timestamp when the task was completed (if applicable) */
    completedAt?: string;
    /** Task IDs that this task blocks (dependents that wait for this task) */
    blocks: string[];
    /** Task IDs that must complete before this task can start (dependencies) */
    blockedBy: string[];
    /** File paths to auto-read when working on this task */
    fileReferences: string[];
    /** Related task IDs that aren't strict dependencies */
    taskReferences: string[];
    /** URLs to docs, issues, PRs, or other external resources */
    urlReferences: string[];
    /** ID of the template used to create this task (if applicable) */
    templateId?: string;
    /** Additional metadata storage */
    metadata: Record<string, any>;
    /** Error message if the task failed */
    error?: string;
    /** Estimated complexity score (1-10) */
    complexity?: number;
    /** Owner of the task (agent name or user ID) */
    owner?: string;
    /** Tags for categorization and filtering */
    tags: string[];
}

/**
 * A reusable task template for common patterns.
 */
export interface TaskTemplate {
    /** Unique identifier for the template */
    id: string;
    /** Human-readable name of the template */
    name: string;
    /** Description of what this template is for */
    description: string;
    /** Base task structure with parameter placeholders */
    baseTask: Partial<Omit<TaskItem, 'id' | 'createdAt' | 'updatedAt'>>;
    /** Parameter definitions for placeholder substitution */
    parameters: Array<{
        name: string;
        description: string;
        default?: any;
        required: boolean;
    }>;
    /** Optional sub-tasks to create alongside the main task */
    subTasks?: Partial<TaskItem>[];
    /** Default file patterns to include as references */
    defaultFilePatterns?: string[];
}

/**
 * Error entry for tracking failures separately from context.
 * Errors are preserved and never included in summaries (Manus approach).
 */
export interface ErrorEntry {
    /** ISO timestamp of when the error occurred */
    timestamp: string;
    /** Name of the tool that produced the error (if applicable) */
    toolName?: string;
    /** The error message or stack trace */
    error: string;
    /** Additional context about where/when the error occurred */
    context?: string;
    /** Number of times this same error recurred recently */
    occurrenceCount: number;
}

/**
 * Configuration for a specialized sub-agent that can be delegated tasks.
 */
export interface SubAgent {
    /** Name used to identify the agent in the delegation tool */
    name: string;
    /** Description of what this agent specializes in */
    description: string;
    /** The core persona and operating rules for the sub-agent */
    systemPrompt: string;
    /** Execution model for the sub-agent */
    mode?: 'custom' | 'general-purpose';
    /** Custom tool definitions (object) or explicit tool names to include (deprecated, use allowedTools) */
    tools?: string[] | Record<string, Tool<any, any>>;
    /** Whitelist of inherited tool names to allow (undefined = all inherited tools allowed) */
    allowedTools?: string[];
    /** Blacklist of tool names to block (takes precedence over allowedTools) */
    blockedTools?: string[];
    /** Optional specific model to use for this sub-agent */
    model?: LanguageModel;
    /** Whether this sub-agent may delegate further work */
    allowSubdelegation?: boolean;
    /** Max reasoning steps for this sub-agent's run (default: 30). */
    maxSteps?: number;
    /** Whether to persist sub-agent artifacts for audit/debugging */
    artifactMode?: 'always' | 'errors-only' | 'never';
    /** Optional approval policy for custom sub-agent tools */
    toolsRequiringApproval?: ToolsRequiringApprovalConfig;
    /**
     * Optional plugin instances for a custom sub-agent.
     */
    plugins?: Plugin[];
    /**
     * @deprecated Use mode: 'general-purpose' instead.
     */
    inheritPlugins?: boolean;
    /** @deprecated Use plugins instead - kept for backward compatibility */
    middleware?: Plugin[];
}

/**
 * Interface for agent plugins that can extend capabilities.
 *
 * Plugins provide tools and lifecycle hooks that run at specific points
 * during agent execution. Hooks that duplicate AI SDK functionality are avoided.
 *
 * @example
 * ```ts
 * const myPlugin: Plugin = {
 *   name: 'MyPlugin',
 *   tools: { myTool },
 *   modifySystemPrompt: (prompt) => prompt + '\\n\\nAdditional instructions...',
 *   onStreamContextReady: ({ writer }) => writer.writeStatus('Ready'),
 *   onError: (error) => console.error('Tool failed:', error),
 *   waitReady: async () => { await initialize(); },
 * }
 * ```
 */
export interface Plugin {
    /** Display name of the plugin */
    name: string;

    /** Optional collection of tools provided by this plugin to the agent */
    tools?: Record<string, any>;

    /**
     * Hook to modify settings for each step (runs before model call).
     * This receives the AI SDK's prepareStep options and can return modifications.
     * The options include: steps, stepNumber, model, messages, system, experimental_context
     *
     * Can return either:
     * - void/undefined for side effects only
     * - An object with modifications (model, toolChoice, activeTools, system, messages, etc.)
     */
    prepareStep?: (options: {
        steps: any[];
        stepNumber: number;
        model: LanguageModel;
        messages: ModelMessage[];
        system?: string | any;
        experimental_context?: unknown;
    }) => (
            | void
            | undefined
            | Promise<void | undefined>
            | {
                model?: LanguageModel;
                toolChoice?: any;
                activeTools?: string[];
                system?: string | any;
                messages?: ModelMessage[];
                experimental_context?: unknown;
            }
            | undefined
            | Promise<{
                model?: LanguageModel;
                toolChoice?: any;
                activeTools?: string[];
                system?: string | any;
                messages?: ModelMessage[];
                experimental_context?: unknown;
            } | undefined>
            | Promise<void | {
                model?: LanguageModel;
                toolChoice?: any;
                activeTools?: string[];
                system?: string | any;
                messages?: ModelMessage[];
                experimental_context?: unknown;
            } | undefined>
        );

    /** Function to modify or extend the system prompt (can be async) */
    modifySystemPrompt?: (prompt: string) => string | Promise<string>;

    /** Hook executed when a tool execution starts (AI SDK v6) */
    onInputStart?: (args: any) => void;

    /** Hook executed when tool input delta is available (AI SDK v6) */
    onInputDelta?: (delta: string) => void;

    /** Hook executed when full tool input is available (AI SDK v6) */
    onInputAvailable?: (args: any) => void;

    /** Optional promise to wait for during initialization (e.g., sandbox startup) */
    waitReady?: () => Promise<void>;

    /** Optional hook to receive the full stream context for real-time UI updates */
    onStreamContextReady?: (context: PluginStreamContext) => void;

    /**
     * Optional hook to receive a raw data stream writer for real-time UI updates.
     * @deprecated Prefer onStreamContextReady() and DataStreamWriter.
     */
    onStreamReady?: (writer: UIMessageStreamWriter<VibesUIMessage>) => void;

    /** Optional hook executed when the stream finishes (successful completion) */
    onStreamFinish?: (result: any) => Promise<void>;

    /**
     * Optional hook executed when a tool fails after all retries.
     * This is called after the tool execution fails and has exhausted all retry attempts.
     * Plugins can use this to react to tool failures (e.g. error analysis).
     */
    onError?: (error: Error) => void | Promise<void>;

    // REMOVED: beforeModel - use prepareStep instead (AI SDK built-in)
    // REMOVED: onStepFinish - use ToolLoopAgent.onStepFinish (AI SDK built-in)
}

/**
 * Represents the persistent state of an agent session.
 */
export interface AgentState {
    /** Combined message history */
    messages: ModelMessage[];
    /** Context summary for long-running sessions */
    summary?: string;
    /** Arbitrary session metadata */
    metadata: Record<string, any>;
}

/**
 * @deprecated Use VibesDataParts from './streaming/streaming.ts' instead
 * This is kept for backwards compatibility
 */
export type AgentDataParts = import('./streaming/streaming.js').VibesDataParts;

/**
 * @deprecated Use VibesUIMessage from './streaming/streaming.ts' instead
 * This is kept for backwards compatibility
 */
export type AgentUIMessage = import('./streaming/streaming.js').VibesUIMessage;

/**
 * Re-export commonly used streaming types and utilities
 */
export type {
    PluginStreamContext,
    VibesDataParts,
    VibesUIMessage,
} from './streaming/streaming.js';

export {
    createDataStreamWriter,
    createPluginStreamContext,
    createScopedUIMessageStreamWriter,
    DataStreamWriter,
    DataStreamOperation,
} from './streaming/streaming.js';

/**
 * Configuration for initializing a AgentHarness instance.
 */
export interface AgentHarnessConfig {
    /** The AI model to use */
    model: LanguageModel;
    /** The base system instructions */
    instructions: string;
    /** Optional display name for the agent (used in notifications) */
    name?: string;
    /** Custom instructions to extend the base system prompt */
    systemPrompt?: string;
    /** Additional custom tools available to the agent */
    tools?: Record<string, Tool<any, any>>;
    /** Maximum number of reasoning steps per invocation (default: 20) */
    maxSteps?: number;
    /** Optional custom stop condition(s) for the tool loop */
    stopWhen?: StopCondition<ToolSet> | Array<StopCondition<ToolSet>>;
    /** Maximum messages before context compression kicks in (default: 30) */
    maxContextMessages?: number;
    /** Model context window in tokens. Drives token-based compression. (default: 128000) */
    contextWindow?: number;
    /** Fraction of the context window at which compression kicks in, 0–1 (default: 0.7) */
    contextCompressionRatio?: number;
    /**
     * Minimum character length a single tool/assistant payload must reach
     * before restorable in-place compression will shrink it (default: 3000).
     * Raise it to let larger reads survive verbatim.
     */
    compressionThreshold?: number;
    /**
     * Fraction of the context window (0–1) the WHOLE conversation must reach
     * before per-message restorable compression runs at all (default: 0.7).
     * Below this, large reads are kept intact even if individually over
     * `compressionThreshold` — no gutting a big file read in an otherwise-empty
     * context. Set 0 to compress eagerly (legacy behaviour).
     */
    compressionGateRatio?: number;
    /**
     * Whether this agent emits the live context-usage gauge (default: true).
     * Set false for sub-agents so their (smaller) context doesn't clobber the
     * main conversation's gauge in the UI.
     */
    emitContextGauge?: boolean;
    /** Model temperature for controlling randomness */
    temperature?: number;
    /** Maximum retries for a single failing tool call (default: 2) */
    maxRetries?: number;
    /**
     * Tool-retry policy. `maxTotalRetries` caps retries across the WHOLE run
     * (default 20), so a transiently-failing tool can't keep retrying on every
     * call. Only transient errors (network / rate-limit / timeout / 5xx) are
     * retried at all; deterministic failures fail fast.
     */
    toolRetry?: { maxTotalRetries?: number };
    /** Callback for step progress updates (matches AI SDK's StepResult) */
    onStepFinish?: (stepResult: StepResult<ToolSet>) => void | Promise<void>;
    /** Custom plugins to extend agent behavior */
    plugins?: Plugin[];
    /** Enable telemetry for observability (default: false) */
    enableTelemetry?: boolean;
    /** The base directory for filesystem operations (e.g., 'workspace') */
    workspaceDir?: string;
    /**
     * Per-session plugin-state directory (plan.md, tasks.json, scratchpad.md,
     * tracked_files.json). Defaults to `workspaceDir`. For a workspace session
     * the sandbox root (`workspaceDir`) is the SHARED project dir, while this
     * points at `{projectDir}/.vibes/sessions/{sessionId}/` so per-session state
     * stays isolated.
     */
    stateDir?: string;
    /**
     * Cross-session shared-state directory (memories.json, workflows.json).
     * Defaults to a value derived from `workspaceDir`. Set explicitly so that
     * an opened external repo never receives global vibes state.
     */
    sharedDir?: string;
    /** List of tool names that require explicit user approval before execution */
    toolsRequiringApproval?: ToolsRequiringApprovalConfig;
    /** Optional whitelist of tool names allowed for this agent instance */
    allowedTools?: string[];
    /** Optional blacklist of tool names to block (takes precedence over allowedTools) */
    blockedTools?: string[];
    /**
     * Per-run budgets (token / cost / tool-call caps). Enforced as native
     * `stopWhen` conditions — the loop halts once a cap is reached.
     */
    budgets?: BudgetConfig;
    /**
     * Stuck-loop detection: halt the run when the agent repeats the same tool
     * call (same name + input) too many times in a short window. Enforced as a
     * native `stopWhen` condition, like {@link budgets}.
     */
    loopDetection?: LoopDetectionConfig;
    /**
     * Adaptive reasoning effort: pick a model reasoning-effort tier from the
     * request's apparent complexity and pass it via provider-namespaced
     * `providerOptions`. `true` enables it with defaults; an object enables it
     * with options; omit/false to disable. No-op on models without reasoning.
     */
    adaptiveReasoning?: boolean | AdaptiveReasoningConfig;
    /**
     * Redact known secrets (API keys, tokens, env assignments) from tool
     * results before they reach the model context or the stream (default true).
     * Set false in a fully trusted environment.
     */
    redactToolIO?: boolean;
}

/**
 * Result returned by AgentHarness.generate()
 * Extends GenerateTextResult with additional agent-specific fields
 */
export interface AgentHarnessGenerateResult<TOOLS extends ToolSet = ToolSet>
    extends GenerateTextResult<TOOLS, any, never> {
    /** The current agent state after generation */
    state: AgentState;
    /** Tool errors that occurred during generation (if any) */
    toolErrors?: Array<unknown>;
}

/**
 * Result returned by AgentHarness.stream() - same as StreamTextResult from AI SDK
 * Using ToolSet for tool types due to dynamic tool registration
 */
export type AgentHarnessStreamResult = StreamTextResult<ToolSet, any, never>;
